# config.yaml
paths:
  proj_root: ${hydra:runtime.cwd}/..  # Set relative to current working directory
  data_dir: ${paths.proj_root}/data
  raw_data_dir: ${hydra:runtime.cwd}/../data/raw
  interim_data_dir: ${paths.data_dir}/interim
  processed_data_dir: ${hydra:runtime.cwd}/../data/processed
  external_data_dir: ${paths.data_dir}/external
  models_dir: ${paths.proj_root}/models
  reports_dir: ${paths.proj_root}/reports
  figures_dir: ${paths.reports_dir}/figures
  
preprocessing:
  drop_cols: ['PassengerId', 'Name', 'Ticket']
  cat_features: ["Sex", "Cabin", "Embarked"]
  num_features: ["Age"]
  passthrough_features:  ["Survived", "Pclass", "SibSp", "Parch", "Fare"]
  test_size: 0.3
  random_state: 42

imputation:
  cat_strategy: "most_frequent"
  num_strategy: "mean"

training:
  test_size: 0.3
  random_state: 42
  cv_folds: 5
  scoring_metric: "accuracy"
  target_column: "Survived"

models:
  logistic_regression:
    max_iter: 200

hyperparameters:
  logistic_regression:
    C: [0.001, 0.01, 0.1, 1, 10, 100]
    solver: ["lbfgs", "liblinear"]
  
  random_forest:
    n_estimators: [50, 100, 200]
    max_depth: [10, 20, null]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
  
logging:
  use_tqdm: true